### ISSUE TITLE
Password vaildation not giving feedback

### ISSUE THREAD

**Issue by ThejasKiranPS** [ThejasKiranPS/tweet-thread-saver#2]
If we enter weak passwords without any digits or both upper case and lower case, the form doesn't give any alert or feedback and just simply do nothing instead of showing an error or popup message.

Suggeste sol: disable password validation in django and we can add this feature with proper feedback to client in v1.2

**Comment by amalpaul54111** [comment]
yeah, sure will start working on it shortly.

**Comment by amalpaul54111** [comment]
It has been resolved recently
